language: python

python:
  - 3.6

os:
  - linux
  - osx

notifications:
  email: false

git:
  depth: 3
      
install:
    - pip -q install coveralls
    
# no -v without run_module_suite()
script: coverage run findssh.py 

after_success: coveralls
