language: python

notifications:
  email: false

git:
  depth: 3
  
os:
    - osx
    - linux

install:
    - pip install -q coverage

script:
    - coverage run findssh.py

after_success:
    - coveralls
