language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
# - 3.8-dev # buggy in travis
- 3.7

matrix:
  include:
  - os: linux
    name: Install Test
    python: 3.7
    install:
    - python setup.py install
    - pip install $(basename $TRAVIS_REPO_SLUG)[tests,full]
    script:
    - cd $HOME
    - python -m pytest $TRAVIS_BUILD_DIR/tests
  - os: linux
    name: PEP8 MyPy Covs
    python: 3.7
    install: pip install -e .[tests,cov]
    script:
    - flake8
    - mypy .
    after_success:
    - pytest --cov
    - coveralls
  - os: osx
    language: minimal
    install: pip3 install -e .[tests]
#  - os: windows
#    language: minimal
#    before_install:
#    - choco install python3
#    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

install: pip install -e .[tests]

script: pytest -rsv

