notifications:
  email: false

git:
  depth: 1

env: pyv=3.5

matrix:
  include:
    - os: osx
        env: osv=MacOSX
        osx_image: xcode7.3

    - os: linux
        env: osv=Linux
        sudo: required
        dist: trusty

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-$osv-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH

install:
    - conda create --yes -n test python=$pyv
    - source activate test
    - pip -q install coveralls
    - pip -q install -r requirements.txt

script:
    - coverage run findssh.py

after_success:
    - coveralls
