# this also works great on osx, but I disabled osx to conserve Travis-CI resources.
language: python
fast_finish: true

python:
  - 3.6
  - "3.7-dev" 
  
os:
  - linux
#  - osx

group: travis_latest

#env:
#  - TRAVIS_PYTHON_VERSION=3.6


git:
  depth: 3

#before_install:
#    - if [[ $TRAVIS_OS_NAME == osx ]]; then
#        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
#      else
#        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#      fi

#    - bash miniconda.sh -b -p $HOME/miniconda
#    - export PATH=$HOME/miniconda/bin:$PATH
#    - hash -r

#    - conda config --set always_yes yes --set changeps1 no
#    - conda update -q conda
#    - conda create -n test python=$TRAVIS_PYTHON_VERSION
#    - source activate test
#    - pip -q install coveralls


install: pip -q install -e .[tests]

script:
  - python findssh.py
  - mypy findssh.py
  - flake8


after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then 
    coverage run findssh.py;
    coveralls; 
    fi
